from __future__ import annotations

import ast
import re
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "cts_cm"

FORBIDDEN = (
    "reproduction of",
    "re-implementation",
    "based on the paper",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "cutting-edge",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "it's worth noting",
    "in conclusion",
    "state-of-the-art",
    "comprehensive",
)
EMOJI = re.compile(r"[\U0001F000-\U0001FAFF☀-⛿✀-➿⬀-⯿]")


def _sources() -> list[Path]:
    return sorted(PACKAGE.rglob("*.py"))


def test_sources_have_no_comments() -> None:
    for path in _sources():
        with tokenize.open(path) as handle:
            for token in tokenize.generate_tokens(handle.readline):
                assert token.type != tokenize.COMMENT, f"comment in {path.name}"


def test_sources_have_no_docstrings() -> None:
    targets = (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)
    for path in _sources():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, targets):
                assert ast.get_docstring(node) is None, f"docstring in {path.name}"


def test_no_forbidden_phrases() -> None:
    scanned = [*_sources(), ROOT / "README.md"]
    for path in scanned:
        text = path.read_text(encoding="utf-8").lower()
        for phrase in FORBIDDEN:
            assert phrase not in text, f"{phrase!r} in {path.name}"


def test_no_emoji() -> None:
    scanned = [*_sources(), ROOT / "README.md"]
    for path in scanned:
        assert EMOJI.search(path.read_text(encoding="utf-8")) is None, f"emoji in {path.name}"
